"""Independent input-contract tests; all generated spectra are synthetic."""

from dataclasses import replace
import hashlib

import numpy as np
import pytest

from pysnspd.experimental.material_admission import (
    AdmissionPolicy, ENERGY_PER_AXIS_UNIT, KB_J_K, MaterialAdmissionError,
    MaterialSpec, admit_material_table, audit_material_table,
)


def make_table(tmp_path, unit="THz", *, n=1001):
    energy = np.linspace(0, 8 * ENERGY_PER_AXIS_UNIT["THz"], n)
    alpha = 0.5 * (energy / energy[-1]) ** 2
    dos_J = 9 * energy**2 / energy[-1]**3
    scale = ENERGY_PER_AXIS_UNIT[unit]
    data = np.c_[energy / scale, alpha, dos_J * scale]
    path = tmp_path / (unit.replace("/", "_") + ".dat")
    np.savetxt(path, data, fmt="%.17e")
    spec = MaterialSpec(
        material_id="synthetic-debye", axis_unit=unit,
        phdos_unit="states/(rad/s)" if unit == "rad/s" else f"states/{unit}",
        normalization_basis="atom", atoms_per_basis=1, basis_density_m3=5e28,
        source_url="synthetic:analytic-debye", source_revision="test-v1",
        raw_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
        unit_evidence="Generated with exact SI Planck/electron-volt conversions.",
        normalization_evidence="Analytic integral of 9 E^2 / E_D^3 is 3 per atom.",
        provenance_evidence="Generated by this test; no material interpretation.",
        units_verified=True, normalization_verified=True, provenance_verified=True,
        synthetic=True,
    )
    return path, spec, data


def rewrite(path, spec, data):
    np.savetxt(path, data, fmt="%.17e")
    return replace(spec, raw_sha256=hashlib.sha256(path.read_bytes()).hexdigest())


def issue_codes(audit):
    return {issue["code"] for issue in audit.issues}


@pytest.mark.parametrize("unit", ["THz", "meV", "eV", "J", "rad/s"])
def test_energy_unit_jacobians_preserve_modes_energy_and_lambda(tmp_path, unit):
    base_path, base_spec, _ = make_table(tmp_path, "THz")
    base = admit_material_table(base_path, base_spec)
    path, spec, _ = make_table(tmp_path, unit)
    material = admit_material_table(path, spec)
    np.testing.assert_allclose(material.omega_J, base.omega_J, rtol=5e-16, atol=1e-36)
    np.testing.assert_allclose(material.g_ph_per_m3_J, base.g_ph_per_m3_J, rtol=5e-16)
    np.testing.assert_allclose(material.alpha2F, base.alpha2F, rtol=0, atol=0)
    assert material.thermal_energy_density(30) == pytest.approx(base.thermal_energy_density(30), rel=5e-15)
    assert material.audit.metrics_assuming_declared_units["lambda_ep"] == pytest.approx(0.5, abs=1e-6)
    assert material.audit.status == "ADMITTED_SYNTHETIC"


def test_axis_and_dos_units_are_independent(tmp_path):
    path, spec, data = make_table(tmp_path)
    original = admit_material_table(path, spec)
    data[:, 0] *= ENERGY_PER_AXIS_UNIT["THz"] / ENERGY_PER_AXIS_UNIT["meV"]
    spec = rewrite(path, replace(spec, axis_unit="meV"), data)
    mixed = admit_material_table(path, spec)
    np.testing.assert_allclose(mixed.g_ph_per_m3_J, original.g_ph_per_m3_J)
    assert mixed.thermal_energy_density(4) == pytest.approx(original.thermal_energy_density(4))


def test_atom_and_cell_bases_produce_same_volume_density(tmp_path):
    path, spec, data = make_table(tmp_path)
    per_atom = admit_material_table(path, spec)
    data[:, 2] *= 2
    cell_spec = rewrite(path, replace(spec, normalization_basis="cell", atoms_per_basis=2,
                                     basis_density_m3=spec.basis_density_m3 / 2), data)
    per_cell = admit_material_table(path, cell_spec)
    np.testing.assert_array_equal(per_cell.g_ph_per_m3_J, per_atom.g_ph_per_m3_J)
    assert per_cell.audit.metrics_assuming_declared_units["expected_modes_per_basis"] == 6
    assert per_cell.thermal_energy_density(300) == per_atom.thermal_energy_density(300)


@pytest.mark.parametrize("failure,code", [
    ("negative_dos", "NEGATIVE_DOS"), ("negative_alpha", "NEGATIVE_ALPHA2F"),
    ("support", "INCOMPATIBLE_SUPPORT"), ("duplicate", "INVALID_AXIS"),
    ("unsorted", "INVALID_AXIS"), ("negative_axis", "INVALID_AXIS"),
    ("nan", "NONFINITE_TABLE"), ("infinity", "NONFINITE_TABLE"),
    ("extra_column", "TABLE_SHAPE"), ("missing_zero", "INCOMPLETE_LOW_ENERGY_SUPPORT"),
    ("wrong_norm", "MODE_COUNT"), ("zero_alpha_intercept", "NONZERO_ALPHA2F_AT_ZERO"),
])
def test_invalid_data_are_rejected_without_repair(tmp_path, failure, code):
    path, spec, data = make_table(tmp_path)
    if failure == "negative_dos": data[5, 2] = -1e-30
    elif failure == "negative_alpha": data[5, 1] = -1e-30
    elif failure == "support": data[5, 2] = 0
    elif failure == "duplicate": data[5, 0] = data[4, 0]
    elif failure == "unsorted": data[[4, 5]] = data[[5, 4]]
    elif failure == "negative_axis": data[0, 0] = -1
    elif failure == "nan": data[5, 1] = np.nan
    elif failure == "infinity": data[5, 2] = np.inf
    elif failure == "extra_column": data = np.c_[data, data[:, 2]]
    elif failure == "missing_zero": data = data[1:]
    elif failure == "wrong_norm": data[:, 2] *= 2
    elif failure == "zero_alpha_intercept": data[0, 1] = 1e-50
    spec = rewrite(path, spec, data)
    before = path.read_bytes()
    audit = audit_material_table(path, spec)
    assert code in issue_codes(audit)
    assert audit.status == "REJECTED"
    with pytest.raises(MaterialAdmissionError) as error:
        admit_material_table(path, spec)
    assert code in issue_codes(error.value.audit)
    assert error.value.audit.to_dict()["repairs_applied"] == []
    assert path.read_bytes() == before


@pytest.mark.parametrize("override,code", [
    ({"raw_sha256": "0" * 64}, "SHA256_MISMATCH"),
    ({"axis_unit": "Hz?"}, "UNKNOWN_UNITS"),
    ({"phdos_unit": "arbitrary"}, "UNKNOWN_UNITS"),
    ({"atoms_per_basis": 2}, "INVALID_BASIS"),
    ({"normalization_basis": "ion_or_cell"}, "INVALID_BASIS"),
    ({"basis_density_m3": 0}, "INVALID_DENSITY"),
    ({"basis_density_m3": np.inf}, "INVALID_DENSITY"),
    ({"source_url": ""}, "MISSING_EVIDENCE"),
    ({"normalization_evidence": ""}, "MISSING_EVIDENCE"),
    ({"units_verified": False}, "UNVERIFIED_EVIDENCE"),
    ({"provenance_verified": False}, "UNVERIFIED_EVIDENCE"),
    ({"normalization_verified": False}, "UNVERIFIED_EVIDENCE"),
    ({"alpha2F_convention": "unknown"}, "ALPHA2F_CONVENTION"),
])
def test_metadata_are_not_inferred_from_a_plausible_sum(tmp_path, override, code):
    path, spec, _ = make_table(tmp_path)
    audit = audit_material_table(path, replace(spec, **override))
    assert code in issue_codes(audit)
    assert not audit.admitted


def test_malformed_table_produces_audit_not_repaired_array(tmp_path):
    path, spec, _ = make_table(tmp_path)
    path.write_text("0 1 2\nnot numbers\n")
    spec = replace(spec, raw_sha256=hashlib.sha256(path.read_bytes()).hexdigest())
    assert "TABLE_PARSE_ERROR" in issue_codes(audit_material_table(path, spec))


def test_duplicate_axis_still_reports_diagnostic_integrals_but_never_admits(tmp_path):
    path, spec, data = make_table(tmp_path)
    data = np.insert(data, 10, data[10], axis=0)
    data[10, 2] *= 1.001
    spec = rewrite(path, spec, data)
    audit = audit_material_table(path, spec)
    assert "INVALID_AXIS" in issue_codes(audit)
    assert audit.metrics_assuming_declared_units["zero_width_intervals"] == 1
    assert audit.metrics_assuming_declared_units["signed_modes_per_basis"] == pytest.approx(3, rel=1e-6)


def test_finite_input_overflowing_si_conversion_is_rejected_without_warning(tmp_path):
    path, spec, data = make_table(tmp_path)
    data[5, 2] = 1e308
    spec = rewrite(path, spec, data)
    with np.errstate(all="raise"):
        audit = audit_material_table(path, spec)
    assert "SI_OVERFLOW" in issue_codes(audit)
    assert audit.status == "REJECTED"


def test_si_arrays_are_read_only_and_zero_temperature_is_exact(tmp_path):
    path, spec, _ = make_table(tmp_path)
    material = admit_material_table(path, spec)
    for array in (material.omega_J, material.alpha2F, material.phdos_per_basis_J, material.g_ph_per_m3_J):
        with pytest.raises(ValueError):
            array[0] = 42
    assert material.thermal_energy_density(0) == 0
    assert np.isfinite(material.thermal_energy_density(1e-5))
    for temperature in (-1, np.nan, np.inf):
        with pytest.raises(ValueError):
            material.thermal_energy_density(temperature)


def test_high_temperature_energy_has_three_modes_per_atom(tmp_path):
    path, spec, _ = make_table(tmp_path, n=10001)
    material = admit_material_table(path, spec)
    temperature = 1e8
    ratio = material.thermal_energy_density(temperature) / (3 * spec.basis_density_m3 * KB_J_K * temperature)
    assert ratio == pytest.approx(1, abs=2e-6)


def test_linear_first_bin_contribution_to_lambda_is_included(tmp_path):
    path, spec, data = make_table(tmp_path, n=21)
    data[:, 1] = 0.25 * data[:, 0] / data[-1, 0]
    spec = rewrite(path, spec, data)
    audit = audit_material_table(path, spec)
    assert audit.admitted
    assert audit.metrics_assuming_declared_units["lambda_ep"] == pytest.approx(0.5, abs=1e-15)


def test_normalization_tolerance_is_explicit_not_a_correction(tmp_path):
    path, spec, data = make_table(tmp_path)
    data[:, 2] *= 1.01
    spec = rewrite(path, spec, data)
    assert not audit_material_table(path, spec).admitted
    admitted = admit_material_table(path, spec, policy=AdmissionPolicy(relative_mode_tolerance=0.02))
    assert admitted.audit.metrics_assuming_declared_units["signed_modes_per_basis"] == pytest.approx(3.03, rel=1e-6)
    np.testing.assert_array_equal(admitted.phdos_per_basis_J, data[:, 2] / ENERGY_PER_AXIS_UNIT["THz"])
    with pytest.raises(ValueError):
        AdmissionPolicy(relative_mode_tolerance=1)
