"""Bounded stage-1 material diagnosis; no production calculation or repair.

Run from the repository root. --verify-upstream fetches six small pinned public
tables in memory with a 12-second timeout per file; no DFPT calculation is run.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import replace
import hashlib
import io
import json
from pathlib import Path
import platform
import sys
import time
import urllib.request

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import quad

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from pysnspd.experimental.material_admission import (
    ENERGY_PER_AXIS_UNIT, KB_J_K, MaterialAdmissionError, MaterialSpec,
    admit_material_table, audit_material_table,
)

UPSTREAM_REVISION = "5b6bd747f80016da5ccd51db73c110a8ecc6abf6"
UPSTREAM_URL = "https://github.com/qnngroup/proj-KE-solver"
NBN_RAW_SHA256 = "e94f11273e6c42b7c8fad978b78d119166e241bec1614ee77e4176906fa8f5df"
NBN_PUBLIC_SHA256 = "9aeea0948033d771deedae40da0cb4dc59fef80ac6ea41ac4d3a67b180efc610"
PUBLIC_FILES = {
    "nbn-a2f-ph.dat": NBN_PUBLIC_SHA256,
    "Al-a2f-phdos.dat": "92141ffe404fcf52afcf86c5fbbb3421b6cb3f4378b4204bfa64fb550462bebc",
    "nb-a2f-phdos.dat": "0f5bfe8832085cd7f964481066a6f6a6fde2f3092e3c5d2c5a7dcd521bdf43f7",
    "TiN-prim-a2f-phdos.dat": "291bcc13a45249c856a24d161c35ed0f1557e163d016b872ce958564c21eaebd",
    "Ta-a2f-phdos-soc-THz.dat": "77e40e5ff63fc50c8c8527d94e52b8e7c92ac6c65be060ba3b4958127443ff0d",
    "pb-a2f-phdos-soc-THz.dat": "1a50a601b4cd75609127811adde7d098ebcfeff22490a4a55a5622ca2a6ca267",
}


def checksum(raw):
    return hashlib.sha256(raw).hexdigest()


def verify_public_inputs():
    records = []
    for name, expected in PUBLIC_FILES.items():
        url = f"https://raw.githubusercontent.com/qnngroup/proj-KE-solver/{UPSTREAM_REVISION}/{name}"
        try:
            raw = urllib.request.urlopen(url, timeout=12).read()
            actual = checksum(raw)
            if actual != expected:
                raise ValueError("Pinned public bytes differ from the previously verified SHA-256.")
            axis, alpha, dos = np.loadtxt(io.BytesIO(raw), comments="#").T
            positive = float(np.trapezoid(np.maximum(dos, 0), axis))
            negative = float(np.trapezoid(np.minimum(dos, 0), axis))
            first = raw.splitlines()[0].decode().strip()
            records.append(dict(
                file=name, url=url, sha256=actual, hash_verified=True,
                header=first if first.startswith("#") else None,
                rows=len(axis), raw_dos_integral=positive+negative,
                positive_integral=positive, negative_integral=negative,
                decision="comparison only; material basis not admitted by this measurement",
            ))
        except (OSError, ValueError) as exc:
            records.append(dict(file=name, url=url, hash_verified=False, error=str(exc)))
    return records


def synthetic_definition(path, unit="THz", count=1001):
    cutoff_J = 8 * ENERGY_PER_AXIS_UNIT["THz"]
    energy = np.linspace(0, cutoff_J, count)
    alpha = 0.5 * (energy / cutoff_J) ** 2
    density_J = 9 * energy**2 / cutoff_J**3
    scale = ENERGY_PER_AXIS_UNIT[unit]
    np.savetxt(path, np.c_[energy / scale, alpha, density_J * scale], fmt="%.17e",
               header="Synthetic Debye; axis unit and DOS unit recorded in material_results.json")
    return MaterialSpec(
        material_id="synthetic-Debye-8THz", axis_unit=unit,
        phdos_unit="states/(rad/s)" if unit == "rad/s" else f"states/{unit}",
        normalization_basis="atom", atoms_per_basis=1, basis_density_m3=5e28,
        source_url="synthetic:sandbox/stage1_catalog/audit_materials.py",
        source_revision="stage1-v1", raw_sha256=checksum(path.read_bytes()),
        unit_evidence="Exact SI constants; Omega=h*nu; dimensionless alpha2F=0.5*(Omega/Omega_D)^2.",
        normalization_evidence="Analytic integral of 9*Omega^2/Omega_D^3 from zero to Omega_D is 3 per atom.",
        provenance_evidence="Generated by this runner as an algorithm fixture, without material claims.",
        units_verified=True, normalization_verified=True, provenance_verified=True, synthetic=True,
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nbn-path", required=True, type=Path)
    parser.add_argument("--output-root", default=ROOT / "docs/implementation/stage1", type=Path)
    parser.add_argument("--verify-upstream", action="store_true")
    args = parser.parse_args()
    started = time.perf_counter()
    out = args.output_root
    out.mkdir(parents=True, exist_ok=True)
    figdir = out / "figures"
    figdir.mkdir(exist_ok=True)
    fixture_dir = out / "synthetic_materials"
    fixture_dir.mkdir(exist_ok=True)

    raw = args.nbn_path.read_bytes()
    first_line, separator, payload = raw.partition(b"\n")
    payload_match = checksum(payload) == NBN_PUBLIC_SHA256
    provenance = {
        "repository": UPSTREAM_URL,
        "revision": UPSTREAM_REVISION,
        "file_origin_commit": "798d8bbab6d28467574d0c95398bc3d2c0dd0686",
        "public_url": f"{UPSTREAM_URL}/blob/{UPSTREAM_REVISION}/nbn-a2f-ph.dat",
        "public_sha256": NBN_PUBLIC_SHA256,
        "local_sha256": checksum(raw),
        "local_bytes": len(raw),
        "header_added_bytes": len(first_line + separator),
        "payload_sha256": checksum(payload),
        "payload_matches_published_file": payload_match,
        "public_file_has_header": False,
        "published_solver_url": f"{UPSTREAM_URL}/blob/{UPSTREAM_REVISION}/solver.m#L93-L113",
        "published_solver_input": "nbn-a2f-ph_2.dat",
        "published_solver_input_present_in_repository": False,
        "published_solver_unit_conversion": "Omega=h*nu; DOS_per_eV=DOS_column/h, for its missing _2 input",
        "published_solver_negative_policy": "F<1e-8 set to zero in lines 112-113; not adopted",
        "license_url": f"{UPSTREAM_URL}/blob/{UPSTREAM_REVISION}/LICENSE",
        "source_conclusion": "Numeric payload traced; its units and atom/cell normalization remain unverified.",
    }
    nbn_spec = MaterialSpec(
        material_id="NbN-Simon-unadmitted", axis_unit="THz", phdos_unit="states/THz",
        normalization_basis="atom", atoms_per_basis=1, basis_density_m3=48e27,
        source_url=provenance["public_url"], source_revision=UPSTREAM_REVISION,
        raw_sha256=NBN_RAW_SHA256,
        unit_evidence="Unverified local header; absent from the byte-identical public numeric payload.",
        normalization_evidence="Unverified atom basis: article calls N ion density; file count is not 3 or 6.",
        provenance_evidence="SHA-256 of local file excluding its added first line matches the pinned public payload.",
        provenance_verified=payload_match,
    )
    nbn_audit = audit_material_table(args.nbn_path, nbn_spec)
    rejected = False
    try:
        admit_material_table(args.nbn_path, nbn_spec)
    except MaterialAdmissionError:
        rejected = True
    assert rejected and nbn_audit.status == "REJECTED"

    synthetic_records = []
    baseline = None
    for unit in ("THz", "meV", "eV", "J", "rad/s"):
        path = fixture_dir / f"debye_{unit.replace('/', '_')}.dat"
        spec = synthetic_definition(path, unit)
        material = admit_material_table(path, spec)
        value = material.thermal_energy_density(30)
        if baseline is None:
            baseline = value
        synthetic_records.append(dict(
            unit=unit, audit=material.audit.to_dict(), energy_at_30K_J_m3=value,
            relative_energy_difference_to_THz=abs(value / baseline - 1),
            file=str(path.relative_to(out)),
        ))

    cutoff_J = 8 * ENERGY_PER_AXIS_UNIT["THz"]
    temperature = 30.
    reference = 5e28 * quad(
        lambda y: 9 * cutoff_J * y**3 / np.expm1(cutoff_J * y / (KB_J_K * temperature)),
        0, 1, epsabs=1e-35, epsrel=3e-13,
    )[0]
    convergence = []
    for count in (101, 501, 1001):
        path = fixture_dir / f"debye_convergence_{count}.dat"
        spec = synthetic_definition(path, count=count)
        material = admit_material_table(path, spec)
        energy = material.thermal_energy_density(temperature)
        convergence.append(dict(nodes=count, energy_J_m3=energy,
                                relative_error_to_adaptive_integral=abs(energy/reference-1),
                                relative_modes_error=material.audit.metrics_assuming_declared_units["relative_mode_error"]))

    axis, alpha, dos = np.loadtxt(args.nbn_path).T
    duplicate_pairs = [
        {"zero_based_row": int(i), "axis_value": float(axis[i]),
         "alpha2F_pair": [float(alpha[i]), float(alpha[i+1])],
         "phdos_pair": [float(dos[i]), float(dos[i+1])]}
        for i in np.flatnonzero(np.diff(axis) == 0)
    ]
    increments = (dos[:-1] + dos[1:]) / 2 * np.diff(axis)
    cumulative = np.r_[0, np.cumsum(increments)]
    plt.rcParams.update({"font.size": 10, "axes.spines.top": False, "axes.spines.right": False})
    fig, axes = plt.subplots(1, 2, figsize=(10.2, 3.7), layout="constrained")
    axes[0].plot(axis, dos, color="#2c5972", lw=1.5, label="Columna original")
    axes[0].fill_between(axis, dos, 0, where=dos < 0, color="#cb6251", label="DOS negativa")
    axes[0].set(xlabel="Eje numérico (cabecera local: THz)", ylabel="DOS original (unidad sin certificar)")
    axes[0].legend(fontsize=8)
    axes[1].plot(axis, cumulative, color="#2c5972", label="Integral bajo la cabecera local")
    axes[1].axhline(3, color="#61705a", ls="--", label="3 modos / átomo, si ésta fuera la base")
    axes[1].set(xlabel="Límite del eje numérico", ylabel="Conteo bajo la convención declarada")
    axes[1].legend(fontsize=8)
    fig.suptitle("Etapa 1: NbN rechazado; procedencia numérica identificada")
    for suffix in ("png", "pdf"):
        fig.savefig(figdir / f"material_admission.{suffix}", dpi=180)
    plt.close(fig)
    with (out / "material_quadrature.csv").open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(convergence[0]))
        writer.writeheader()
        writer.writerows(convergence)
    np.savetxt(out / "material_nbn_audit.csv", np.c_[axis, dos, cumulative], delimiter=",",
               header="axis_as_supplied,phdos_as_supplied,cumulative_integral_as_supplied", comments="")

    public_comparison = verify_public_inputs() if args.verify_upstream else []
    result = {
        "schema": "pysnspd.experimental.material-admission.stage1.v1",
        "runtime_seconds": time.perf_counter() - started,
        "python": platform.python_version(), "numpy": np.__version__,
        "production_imports_or_changes": False,
        "nbn_audit": nbn_audit.to_dict(), "nbn_strict_admission_rejected": rejected,
        "nbn_duplicate_axis_pairs": duplicate_pairs,
        "source_provenance": provenance, "upstream_online_comparison": public_comparison,
        "synthetic_unit_invariance": synthetic_records,
        "synthetic_quadrature_convergence": convergence,
        "synthetic_reference_energy_at_30K_J_m3": reference,
        "decision": "Proceed with synthetic structural tests; NbN absolute phonon energy and rates remain blocked.",
        "missing_physical_inputs": [
            "Verified ordinate units of the published NbN numeric file",
            "Documented complete phonon basis and matching basis density",
            "Positive, physically valid phonon DOS without silent clipping",
            "Single-valued spectral abscissas with documented treatment of four conflicting duplicate pairs",
        ],
        "admission_limit": "Metadata evidence is an explicit reviewed contract; sum rules alone cannot establish provenance or missing high-energy support.",
    }
    assert max(r["relative_energy_difference_to_THz"] for r in synthetic_records) < 1e-12
    assert convergence[-1]["relative_error_to_adaptive_integral"] < 1e-7
    assert checksum(args.nbn_path.read_bytes()) == checksum(raw)
    (out / "material_results.json").write_text(json.dumps(result, indent=2, ensure_ascii=False, allow_nan=False) + "\n", encoding="utf-8")
    print(json.dumps({"runtime_seconds": result["runtime_seconds"], "NbN": nbn_audit.status,
                      "NbN_issues": [i["code"] for i in nbn_audit.issues],
                      "payload_matches_upstream": payload_match,
                      "max_unit_energy_difference": max(r["relative_energy_difference_to_THz"] for r in synthetic_records),
                      "quadrature_relative_error": convergence[-1]["relative_error_to_adaptive_integral"]}))


if __name__ == "__main__":
    main()
